import {MigrationInterface, QueryRunner, Table, TableColumn} from "typeorm";

export class parcelas1634569346869 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.createTable(new Table({
            name:'parcelas',
            columns:[
                {
                    name:'id',
                    type:'integer',
                    isPrimary:true,
                    isGenerated:true,
                    generationStrategy: 'increment',
                },
                {
                    name:'nome',
                    type:'varchar',
                    isNullable:false
                },
                {
                    name:'area',
                    type:'decimal',
                    precision:5,
                    scale:3,
                    isNullable:true
                },
                {
                    name:'data_transplantio',
                    type:'timestamp',
                    isNullable:false
                },
                {
                    name:'esp_linhas',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'esp_emissores',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'vazao',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'eficiencia_irrigacao',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'taxa_aplicacao',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'esp_plantas',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'projecao_rama_max',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'porcao_area',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'kl',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'cap_agua',
                    type:'decimal',
                    precision:5,
                    scale:2,
                    isNullable:true
                },
                {
                    name:'qtd_max_pulso',
                    type:'int',
                    isNullable:true
                },
                {
                    name:'qtd_min_pulso',
                    type:'int',
                    isNullable:true
                },
                {
                    name:'duracao_media_pulso',
                    type:'int',
                    isNullable:true
                },
                {
                    name:'com_transmissividade_solo',
                    type:'boolean',
                    default:false
                },
                {
                    name:'com_eficiencia_irrigacao',
                    type:'boolean',
                    default:false
                },
                {
                    name:'created_at',
                    type:'timestamp',
                    default:'now()'
                },
                {
                    name:'updated_at',
                    type:'timestamp',
                    default:'now()'
                }
            ]
        }))

    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.dropTable('parcelas')
    }

}
